# 文字コード
set-window-option -g utf8 on
set-window-option -g status-utf8 on

# ステータスバーの表示
set-option -g status-fg   black
set-option -g status-bg   colour111
set-option -g status-attr default
# ステータスバーの左側にホスト名を表示
set-option -g status-left " #h"
set-option -g status-left-fg   colour160
set-option -g status-left-bg   default
set-option -g status-left-length 40
set-option -g status-left-attr bold
# ステータスバーの右側に日次を表示
set-option -g status-right " [%m/%d %H:%M] "
set-option -g status-right-fg   colour12
set-option -g status-right-bg   colour231
set-option -g status-right-length 16
set-option -g status-right-attr bold

# ウィンドウ一覧部における現在非アクティブなウィンドウの項目の表示
set-window-option -g window-status-fg   black
set-window-option -g window-status-bg   default
set-window-option -g window-status-attr default

# ウィンドウ一覧部における現在アクティブなウィンドウの項目の表示
set-window-option -g window-status-current-fg   colour15
set-window-option -g window-status-current-bg   colour240
set-window-option -g window-status-current-attr bold

# pane 同士の境界線
set -g pane-active-border-fg white

# 新しいウィンドウ/ペイン分割 (ディレクトリ引き継ぎ非対応)
bind C-c new-window             # 新しいウィンドウ
bind 2 split-window -v          # 上下に分割する
bind 3 split-window -h          # 左右に分割する

# message text
set-option -g message-bg colour15
set-option -g message-fg colour21
